- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - automake
      - build-essential
      - curl
      - file
      - git
      - libyaml-dev
      - libprotobuf-dev
      - m4
      - perl
      - pkg-config
      - procps
      - unzip
      - valgrind
      - zlib1g-dev
