- name: Download Kong source code
  get_url:
    url: https://codeload.github.com/Kong/kong/tar.gz/refs/tags/2.8.3
    dest: /opt/2.8.3.tar.gz
    mode: 0755

- name: Extract Kong source code
  ansible.builtin.unarchive:
    src: /opt/2.8.3.tar.gz
    dest: /opt
    remote_src: yes

- name: Set environment variables
  shell: |
    export PATH="$PATH:/opt/kong-build-tools/openresty-build-tools/build/openresty/bin:/opt/kong-build-tools/openresty-build-tools/build/openresty/nginx/sbin:/opt/kong-build-tools/openresty-build-tools/build/luarocks/bin"
    export OPENSSL_DIR="/opt/kong-build-tools/openresty-build-tools/build/openssl"
    eval `luarocks path`

- name: Source .bashrc
  shell: ". /root/.bashrc"
  become: yes

- name: Build and Install Kong
  shell: |
    export PATH="$PATH:/opt/kong-build-tools/openresty-build-tools/build/openresty/bin:/opt/kong-build-tools/openresty-build-tools/build/openresty/nginx/sbin:/opt/kong-build-tools/openresty-build-tools/build/luarocks/bin"
    export OPENSSL_DIR="/opt/kong-build-tools/openresty-build-tools/build/openssl"
    eval `luarocks path`
    /opt/kong-build-tools/openresty-build-tools/build/luarocks/bin/luarocks make
    make install
  args:
    chdir: /opt/kong-2.8.3

- name: Run Kong migrations
  shell: |
    export PATH="$PATH:/opt/kong-build-tools/openresty-build-tools/build/openresty/bin:/opt/kong-build-tools/openresty-build-tools/build/openresty/nginx/sbin:/opt/kong-build-tools/openresty-build-tools/build/luarocks/bin"
    export OPENSSL_DIR="/opt/kong-build-tools/openresty-build-tools/build/openssl"
    eval `luarocks path`
    /opt/kong-2.8.3/bin/kong migrations bootstrap
  args:
    creates: /etc/kong/.bootstrapped
  become: yes

- name: Create Kong systemd service file
  template:
    src: kong-service.j2
    dest: /etc/systemd/system/kong.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Kong service
  systemd:
    name: kong
    enabled: yes
    state: started
  become: yes
