- name: Add Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository to Apt sources
  ansible.builtin.lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ dpkg_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  vars:
    dpkg_architecture: "amd64"
    ansible_distribution_release: "jammy"

- name: Update APT cache with Docker repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
